stages:
  - analysis
  - test
  - build
  - test-build
  - deploy

variables:
  GIT_DEPTH: 1

.tags_win10:
  tags: ["eo", "win10", "arepytools-win"]

.tags_win10_conda:
  tags: ["eo", "win10", "conda"]

.tags_manylinux_2_28:
  tags: ["eotools_manylinux228"]

.tags_conda:
  tags: ["eo", "miniconda3", "official"]

.tags_win10_new:
  tags: ["eotools_win10"]

.tags_deploy:
  tags: ["eo", "deploy"]

# === analysis ===============================================================
# ============================================================================
check_code_compliance_ruff:
  stage: analysis
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s check_format

check_code_compliance_pylint:
  stage: analysis
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s pylint

# === test - unittest ========================================================
# ============================================================================
unittest_linux:
  stage: test
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s unittest -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
  extends: .tags_manylinux_2_28
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit:
        - _build/unittest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: _build/unittest-coverage-*.xml

unittest_win:
  stage: test
  script:
    - . "C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\profile.ps1"
    - conda create -y -n testing python=${PYTHON}
    - conda activate testing
    - python -m pip install nox
    - python -m nox -s unittest -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  extends: .tags_win10_new
  artifacts:
    reports:
      junit:
        - _build/unittest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: _build/unittest-coverage-*.xml

# === test - integration =====================================================
# ============================================================================
# integration_test_linux:
#   stage: test
#   script:
#     - python${PYTHON} -m venv ./ci_test
#     - source ./ci_test/bin/activate
#     - python -m pip install .[cli]
#     - mkdir test_output
#     - sct-testing -r ./tests/integration_tests/test_registry_linux.json -out ./test_output
#   parallel:
#     matrix:
#       - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
#   extends: .tags_manylinux_2_28
#   needs: []

# integration_test_windows:
#   stage: test
#   script:
#     - . "C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\profile.ps1"
#     - conda create -y -n integration_test python=${PYTHON}
#     - conda activate integration_test
#     - python -m pip install -e .[cli]
#     - mkdir -p ./test_output
#     - mkdir -p C:/test_out_reference
#     - mkdir -p C:/test_inputs_copy
#     - echo "Copying NetCDF test resources to disk..."
#     - cp -r C:/chopper/integration_tests/sct/* c:/test_out_reference
#     - cp -r C:/chopper/reference_dataset/sentinel1a/auxiliaries/ETAD_23.SAFE C:/test_inputs_copy/
#     - cp -r C:/chopper/reference_dataset/iceye/products/SM_1899652_93266 C:/test_inputs_copy/
#     - cp -r C:/chopper/reference_dataset/iceye/products/SLH_1835029_91260 C:/test_inputs_copy/
#     - cp -r C:/chopper/reference_dataset/iceye/products/SC_2391740_117355 C:/test_inputs_copy/
#     - cp -r C:/chopper/reference_dataset/cosmo/products/CSKS1_DGM_B_WR_00_HH_RA_FF_20240107043057_20240107043111.h5 C:/test_inputs_copy/
#     - sct-testing -r ./tests/integration_tests/test_registry_windows.json -out ./test_output
#   parallel:
#     matrix:
#       - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
#   extends: .tags_win10_new
#   needs: []

# === build ==================================================================
# ============================================================================
sdist:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_sdist
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist/*.tar.gz

wheel:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_wheel
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist/*.whl

conda_pkg:
  stage: build
  extends:
    - .tags_conda
  script:
    - pip install nox
    - python -m nox -s build_conda_pkg
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist/*.conda

doc:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - yum install -y pandoc
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_doc
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - docs/build/*.zip

# === deploy =================================================================
# ============================================================================
deploy_package:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - eval "$(ssh-agent -s)"
    - for file in dist/*.tar.gz dist/*.whl; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/sct/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/sct/archive;
      done
    - for file in dist/*.conda; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} ${INTERNAL_CONDA_CHANNEL_PATH}/noarch &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc ${INTERNAL_CONDA_CHANNEL_PATH}/noarch;
      done
    - ./.gitlab/ci/conda-forge-update.sh ${INTERNAL_CONDA_CHANNEL_PATH}

deploy_doc:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: '$DEPLOY_DOC == "true"'
  before_script:
    - export PACKAGE_VERSION=v$(grep "__version__" sct/__init__.py | awk -F '"' '{print $2}')
  script:
    - eval "$(ssh-agent)"
    - cat "$DASHBOARD_PRIVATE_KEY" | base64 -d | ssh-add -
    - for file in docs/build/*.zip; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/sct/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/sct/archive;
      done
    - unzip docs/build/*.zip
    - mv *-html-doc ${PACKAGE_VERSION}
    - rsync --stats -r ${PACKAGE_VERSION} sardashboard@intranet.aresys.it:develop/sct/docs
    - ssh sardashboard@intranet.aresys.it "cd develop/sct/docs && rm latest && ln -s ${PACKAGE_VERSION} latest"
