stages:
  - analysis
  - test
  - build
  - test-build
  - deploy

variables:
  GIT_DEPTH: 1

.tags_win10:
  tags: ["eo", "win10", "arepytools-win"]

.tags_win10_conda:
  tags: ["eo", "win10", "conda"]

.tags_manylinux2014:
  tags: ["manylinux2014"]

.tags_manylinux_2_28:
  tags: ["manylinux_2_28"]

.tags_conda:
  tags: ["eo", "miniconda3", "official"]

.tags_deploy:
  tags: ["eo", "deploy"]

# === analysis ===============================================================
# ============================================================================
pylint:
  stage: analysis
  extends:
    - .tags_conda
  script:
    - pip install nox
    - python -m nox -s pylint

format:
  stage: analysis
  extends:
    - .tags_conda
  script:
    - pip install nox
    - python -m nox -s format_check

# === test - unittest ========================================================
# ============================================================================
unittest_linux:
  stage: test
  script:
    - pdm use python${PYTHON}
    - python3 -m pip install nox
    - python3 -m nox -s unittest -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12"]
  extends: .tags_manylinux_2_28
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit:
        - _build/unittest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: _build/unittest-coverage-*.xml

unittest_win:
  stage: test
  script:
    - $py_vers = ${PYTHON}.replace(".", "")
    - pdm use python$py_vers
    - python -m pip install nox
    - python -m nox -s unittest -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12"]
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  extends: .tags_win10
  artifacts:
    reports:
      junit:
        - _build/unittest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: _build/unittest-coverage-*.xml

# === test - integration =====================================================
# ============================================================================
integration_test_linux:
  stage: test
  script:
    - pdm use python3
    - eval $(pdm venv activate)
    - pdm sync -d -G:all
    - pdm integration_tests ./tests/integration_tests/config/linux.toml
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12"]
  extends: .tags_manylinux_2_28
  needs: []

integration_test_windows:
  stage: test
  script:
    - . "C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\profile.ps1"
    - conda create -y -n test python=${PYTHON}
    - conda activate test
    - python -m pip install arepyextras-test
    - python -m pip install setuptools
    - python -m pip install -e .[test]
    - mkdir -p tdir
    - python -m arepyextras.test --config ./tests/integration_tests/config/win10.toml test run ./tests/integration_tests/suite
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12"]
  extends: .tags_win10_conda
  needs: []

# === build ==================================================================
# ============================================================================
build_package:
  stage: build
  extends: .tags_manylinux_2_28
  script:
    - pdm use python3
    - eval $(pdm venv activate)
    - pdm sync -d
    - pdm build
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/dist/*.tar.gz
      - ${SUBPROJECT}/dist/*.whl

conda_pkg:
  stage: build
  extends:
    - .tags_conda
  script:
    - pip install nox
    - python -m nox -s build_conda_pkg
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist/*.tar.bz2

doc:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - yum install -y pandoc
    - python3 -m pip install nox
    - python3 -m nox -s build_doc
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - docs/build/*.zip

# === deploy =================================================================
# ============================================================================
deploy_package:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - eval "$(ssh-agent -s)"
    - for file in dist/*.tar.gz dist/*.whl; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/sct/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/sct/archive;
      done
    - for file in dist/*.tar.bz2; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} ${INTERNAL_CONDA_CHANNEL_PATH}/noarch &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc ${INTERNAL_CONDA_CHANNEL_PATH}/noarch;
      done
    - ./.gitlab/ci/conda-forge-update.sh ${INTERNAL_CONDA_CHANNEL_PATH}

deploy_doc:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: '$DEPLOY_DOC == "true"'
  before_script:
    - export PACKAGE_VERSION=v$(grep "__version__" sct/__init__.py | awk -F '"' '{print $2}')
  script:
    - eval "$(ssh-agent)"
    - cat "$DASHBOARD_PRIVATE_KEY" | base64 -d | ssh-add -
    - for file in ${SUBPROJECT}/docs/build/*.zip; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/sct/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/sct/archive;
      done
    - unzip ${SUBPROJECT}/docs/build/*.zip
    - mv *${SUBPROJECT}*-html-doc ${PACKAGE_VERSION}
    - rsync --stats -r ${PACKAGE_VERSION} sardashboard@intranet.aresys.it:develop/sct/docs
    - ssh sardashboard@intranet.aresys.it "cd develop/sct/docs && rm latest && ln -s ${PACKAGE_VERSION} latest"
