[general]
save_log = true
save_config_copy = true

[point_target_analysis]
perform_irf = true
perform_rcs = true
evaluate_pslr = true
evaluate_islr = true
evaluate_sslr = true
evaluate_localization = true
ale_validity_limits = [99, 99]

[point_target_analysis.corrections]
enable_etad_corrections = true
enable_solid_tides_correction = true
enable_plate_tectonics_correction = true
enable_sensor_specific_processing_corrections = true
enable_ionospheric_correction = false
enable_tropospheric_correction = false
etad_product_path = ""

[point_target_analysis.corrections.ionosphere]
ionospheric_maps_directory = ""
ionospheric_analysis_center = "cor"

[point_target_analysis.corrections.troposphere]
tropospheric_maps_directory = ""
tropospheric_map_grid_resolution = "fine"

[point_target_analysis.advanced_configuration.irf_parameters]
peak_finding_roi_size = [33, 33]
analysis_roi_size = [128, 128]
oversampling_factor = 16
zero_doppler_abs_squint_threshold_deg = 1.0
masking_method = "peak"

[point_target_analysis.advanced_configuration.rcs_parameters]
interpolation_factor = 8
roi_dimension = 128
calibration_factor = 1.0
resampling_factor = 1.0

[radiometric_analysis]
input_quantity = "beta_nought"
azimuth_block_size = 2000
range_pixel_margin = 150
radiometric_correction_exponent = 1.0

[radiometric_analysis.advanced_configuration.profile_extraction_parameters]
outlier_removal = true
smoothening_filter = true
filtering_kernel_size = [11, 11]
outliers_percentile_boundaries = [20, 90]
outliers_kernel_size = [5, 5]

[radiometric_analysis.advanced_configuration.histogram_parameters]
x_bins_step = 10
y_bins_num = 101
y_bins_center_margin = 3

[interferometric_analysis]
azimuth_blocks_number = 100          # this is not the default, default is automatically computed when needed
range_blocks_number = 100            # this is not the default, default is automatically computed when needed
enable_coherence_computation = false
coherence_kernel = [15, 15]
coherence_bins_number = 80
