{% set name = "sct" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ../dist/{{ name }}-{{ version }}.tar.gz

build:
  entry_points:
    - sct = sct.__main__:main
    - sct-rosamond-data-to-csv = sct.cli.utility_commands_cli:convert_rosamond_csv
    - sct-ionospheric-maps-download = sct.cli.utility_commands_cli:download_ionex_tec_maps
    - sct-tropospheric-maps-download = sct.cli.utility_commands_cli:download_tropospheric_vmf3_maps
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - numpy <2
    - pandas
    - jsonschema
    - toml
    - pyproj
    - shapely
    - h5py
    - s1etad
    - ascii-art
    - appdirs
    - arepytools >=1.7.2
    - arepyextras-quality >=2.0.2
    - arepyextras-perturbations >=1.1
    - arepyextras-eo_products >=1.1.0
    - scipy <1.14
    - zarr <3

test:
  imports:
    - sct
  commands:
    - pip check
    - sct --help
    - sct-rosamond-data-to-csv --help
    - sct-ionospheric-maps-download --help
    - sct-tropospheric-maps-download --help
  requires:
    - pip

about:
  summary: SCT (SAR Calibration Toolbox) is the Aresys Python module for SAR products quality analysis.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Aresys srl
